export const AUTHENTICATION_PASS = 'AUTHENTICATED_PASS';
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR';
export const SESSION_EXPIRED = 'SESSION_EXPIRED';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';
export const REGISTER_PASS = 'REGISTER_PASS';
export const REGISTER_FAILED = 'REGISTER_FAILED';
